// USUARIOS

//GET TODOS USERS
#####
GET http://localhost:9000/api/users HTTP/1.1



//GET POR ID

######
GET http://localhost:9000/api/users/64dedc49a52805869731ba68 HTTP/1.1


//GET POR EMAIL

#####
GET http://localhost:9000/api/users/prueba@gmail.com HTTP/1.1




//POST USER UNO SOLO

#####

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Juan",
    "lastname": "Mendez",
    "age": 24
}


//POST VARIOS USUARIOS

#####
POST http://localhost:9000/api/usersMany HTTP/1.1
Content-Type: application/json

[
    {
        "name": "Pepito",
        "lastname": "Perez",
        "age": 45
    },
    {
        "name": "Pepita",
        "lastname": "Lozano",
        "age": 34
    },
    {
        "name": "Juan",
        "lastname": "Arias",
        "age": 32
    }
]




// PUT UNO SOLO

####
PUT http://localhost:9000/api/users/64dedc49a52805869731ba68 HTTP/1.1
Content-Type: application/json

    {
        "name": "Rosario",
        "lastname": "Cruz",
        "age": 40
    }


// PUT VARIOS

#####
PUT http://localhost:9000/api/usersMany HTTP/1.1
Content-Type: application/json

{
    "age": 40
}


#####
PUT http://localhost:9000/api/users/64e005f155f801dd81cf7052 HTTP/1.1
Content-Type: application/json

    {
        "age": 45
    }




//DELETE UNO SOLO

#####
DELETE http://localhost:9000/api/users/64dedc49a52805869731ba68 HTTP/1.1





//ASESORIAS


//GET TODOS ASESORIAS
#####
GET http://localhost:9000/api/asesorias HTTP/1.1





//POST UNO SOLO

#####

POST http://localhost:9000/api/asesorias HTTP/1.1
Content-Type: application/json

    {
        "nombre": "prueba",
        "descripcion": "pruebita"
    }



//POST  VARIOS ASESORIAS
#####
POST http://localhost:9000/api/asesoriasMany HTTP/1.1
Content-Type: application/json

[
    {
        "nombre": "Diseño e Implementaciòn del SG-SST",
        "descripcion": "Acompañamiento y asesoria tecnica en todo lo referente al SG-SST"
    },
    {
        "nombre": "Evaluaciòn inicial del SG-SST",
        "descripcion": "Evaluaciòn inicial de acuerdo a la Res 0312 de estandares minimos de SST"
    },
    {
        "nombre": "Programas de Gestiòn de Riesgos",
        "descripcion": "Diseño e implementaciòn de programas preventivos de acuerdo a riesgos."
    },
    {
        "nombre": "Capacitaciones de SST",
        "descripcion": "Capacitaciones presenciales o virtuales enfocadas en los riesgos de la empresa."
    },
    {
        "nombre": "Matriz de Peligros",
        "descripcion": "Visitas tecnicas para identificar peligros, evaluaciòn y valoraciòn de riesgos"
    },
    {
        "nombre": "Investigaciones de AT y EL",
        "descripcion": "Visitas tecnicas, entrevistas y acompañamiento en accidentes de trabajo y enfermedad laboral"
    },
    {
        "nombre": "Documentaciòn del SG-SST",
        "descripcion": "Documentaciòn virtual y fisica de todos los documentos de acuerdo al PHVA"
    },
    {
        "nombre": "Aplicativo Web de evaluaciòn inicial del SG-SST",
        "descripcion": "Aplicativo evaluaciòn inicial de acuerdo a la Res 0312 de estandares minimos de SST"
    },
    {
        "nombre": "Aplicativo Web para la administraciòn del SG-SST",
        "descripcion": "Aplicativo para la gestiòn y desarrollo del SG-SST"
    }

]





//INHOUSE

//GET TODOS 
#####
GET http://localhost:9000/api/inhouse HTTP/1.1



//POST  VARIOS INHPUSE
#####
POST http://localhost:9000/api/inhouseMany HTTP/1.1
Content-Type: application/json

[
    {
        "nombre":"Tècnico SST",
        "descripcion": "Capacitaciòn, inspecciones, implementaciòn SG-SST",
        "modalidad":"Presencial-medio tiempo"
    },
    {
        "nombre":"Profesional SST",
        "descripcion":"Diseño, implementaciòn del SG-SST, administraciòn del SG-SST, capacitaciòn, investigaciones de AT y EL",
        "modalidad":"Presencial-medio tiempo"
    }

]


//POST REGISTER

#####
POST http://localhost:9000/api/register HTTP/1.1
Content-Type: application/json

{
    "nombreEmpresa": "Empresa Prueba",
    "nit": "123456789-0",
    "numeroEmpleados": 20,
    "representanteLegal": "Maria Rodriguez",
    "actividadEconomica": "Desarrollo de software y servicios de consultoría en tecnología de la información.",
    "email": "correoprueba@gmail.com",
    "password": "pruebac1234"
}



//POST LOGIN

#####
POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
    "nombreEmpresa": "Empresa Prueba",
    "nit": "123456789-0",
    "numeroEmpleados": 20,
    "representanteLegal": "Maria Rodriguez",
    "actividadEconomica": "Desarrollo de software y servicios de consultoría en tecnología de la información.",
    "email": "correoprueba@gmail.com",
    "password": "pruebac1234"
}