// USUARIOS

//GET TODOS USERS
#####
GET http://localhost:9000/api/users HTTP/1.1



//GET POR ID

######
GET http://localhost:9000/api/users/64dedc49a52805869731ba68 HTTP/1.1


//GET POR EMAIL

#####
GET http://localhost:9000/api/users/prueba@gmail.com HTTP/1.1




//POST USER UNO SOLO

#####

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombreEmpresa": "empresa prueba 1",
    "nit": "123",
    "numeroEmpleados": 10,
    "representanteLegal": "juan",
    "actividadEconomica": "producción",
    "email": "prueba1@gmail.com",
    "password": "prueba1"
}

{
    "nombreEmpresa": "empresa prueba 2",
    "nit": "1234",
    "numeroEmpleados": 14,
    "representanteLegal": "pepa",
    "actividadEconomica": "arte",
    "email": "prueba2@gmail.com",
    "password": "prueba2"
}


//POST VARIOS USUARIOS

#####
POST http://localhost:9000/api/usersMany HTTP/1.1
Content-Type: application/json

[
    {
        "nombreEmpresa": "Verdevital S.A.",
        "nit": "543210987-6",
        "numeroEmpleados": 70,
        "representanteLegal": "Juan Morales",
        "actividadEconomica": "Producción y venta de productos naturales para el cuidado personal y el hogar.",
        "email": "verdevital@gmail.com",
        "password": "verde1234"
    },
    {
        "nombreEmpresa": "Delicias Gourmet LTDA",
        "nit": "876543210-1",
        "numeroEmpleados": 40,
        "representanteLegal": "Andrea Ramírez",
        "actividadEconomica": "Elaboración y distribución de alimentos gourmet y productos culinarios.",
        "email": "delicisas@gmail.com",
        "password": "delicias1234"

    },
    {
        "nombreEmpresa": "ConstruMas",
        "nit": "234567890-5",
        "numeroEmpleados": 120,
        "representanteLegal": "Eduardo Silva",
        "actividadEconomica": "Construcción y remodelación de viviendas y espacios comerciales.",
        "email": "constru@gmail.com",
        "password": "constru1234"

    },
    {
        "nombreEmpresa": "EcoCycle Reciclaje Sostenible",
        "nit": "654321098-3",
        "numeroEmpleados": 25,
        "representanteLegal": "Gabriela Fernández",
        "actividadEconomica": "Recolección y procesamiento de materiales reciclables para promover la sostenibilidad ambiental.",
        "email": "eco@gmail.com",
        "password": "eco1234"

    },
    {
        "nombreEmpresa": "ArteVivo Galería",
        "nit": "987654321-0",
        "numeroEmpleados": 12,
        "representanteLegal": "Martín Mendoza",
        "actividadEconomica": "Galería de arte contemporáneo que promueve y vende obras de artistas locales e internacionales.",
        "email": "arte@gmail.com",
        "password": "arte1234"
    }
]




// PUT UNO SOLO

####
PUT http://localhost:9000/api/users/64dedc49a52805869731ba68 HTTP/1.1
Content-Type: application/json

    {
        "name": "Rosario",
        "lastname": "Cruz",
        "age": 40
    }


// PUT VARIOS

#####
PUT http://localhost:9000/api/usersMany HTTP/1.1
Content-Type: application/json

{
    "age": 40
}


#####
PUT http://localhost:9000/api/users/64e005f155f801dd81cf7052 HTTP/1.1
Content-Type: application/json

    {
        "age": 45
    }




//DELETE UNO SOLO

#####
DELETE http://localhost:9000/api/users/64d7e4f2c2e36d8340d08f73 HTTP/1.1
















//SERVICIOS

#####
POST http://localhost:9000/api/serviciosMany HTTP/1.1
Content-Type: application/json

[
    {
        "nombre": "Diseño e Implementación del SG-SST",
        "descripcion": "Acompañamiento y asesoría técnica en todo lo referente al SG-SST."
    },
    {
        "nombre": "Evaluación Inicial del SG-SST",
        "descripcion": "Análisis inicial para evaluar la implementación del SG-SST en la organización de acuerdo a la Resolución 0312 del 2019."
    },
    {
        "nombre": "Capacitaciones en SST",
        "descripcion": "Programas de formación en Seguridad y Salud en el Trabajo para el personal."
    },
    {
        "nombre": "Programas de Gestión de Riesgos",
        "descripcion": "Desarrollo de estrategias para identificar y gestionar riesgos laborales aplicables a la empresa."
    },
    {
        "nombre": "Matriz de Peligros",
        "descripcion": "Identificación de peligros, evaluación y valoración de los riesgos y sus controles asociados"
    },
    {
        "nombre": "Investigación de Accidentes de Trabajo y Enfermedades Laborales",
        "descripcion": "Análisis e investigación de accidentes y enfermedades laborales."
    },
    {
        "nombre": "Plan de Prevención, Preparación y Respuesta ante Emergencias",
        "descripcion": "Diseño e implementación del plan de emergencias incluyendo la formación de brigadas de emergencias."
    },
    {
        "nombre": "Actividades Lúdicas de SST",
        "descripcion": "Actividades recreativas relacionadas con la Seguridad y Salud en el Trabajo"
    },
    {
        "nombre": "Aplicativo Web para Seguimiento del SG-SST",
        "descripcion": "Acceso a la plataforma en línea para ver en tiempo real el avance del SG-SST, recursos y beneficios"
    },
    {
        "nombre": "Inhouse Tecnólogo SST",
        "descripcion": "Tecnólogo en SST medio tiempo en SST disponible en la organización para asesoramiento interno"
    },
    {
        "nombre": "Inhouse Profesional SST",
        "descripcion": "Profesional en SST medio tiempo contratado internamente para apoyar en temas de seguridad laboral"
    },
    {
        "nombre": "Inhouse Especialista SST",
        "descripcion": "Experto en SST medio tiempo incorporado en la organización para gestionar aspectos complejos de seguridad y salud"
    }
]



//GET TODOS SERVICIOS
#####
GET http://localhost:9000/api/servicios HTTP/1.1
# autorizado: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ1Njk1ODZ9.b_WDGr6phUL-DU7g8d9dZLzjV2QuBtp30N3lAKkAgWs




// SEGUIMIENTO


#####
POST http://localhost:9000/api/seguimiento HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxMGYzNDhhNjNjNzMzMzFkNmUxZTZlIiwidXNlcl9yb2xlIjoicmVndWxhciIsImlhdCI6MTY5NTg3MTQ5Nn0.fdmIB_cv_Y3SmxsxtZEqPceTKI40I2rC5eiRnaHt4RI



    {
        "usuario": "6510f348a63c73331d6e1e6e",
        "avance": 70,
        "planear": 20,
        "hacer": 20,
        "verificar": 30,
        "actuar": 10
        
    }


#####
DELETE http://localhost:9000/api/seguimiento/6514dd4ae41d4e3707714166 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxMGYzNDhhNjNjNzMzMzFkNmUxZTZlIiwidXNlcl9yb2xlIjoicmVndWxhciIsImlhdCI6MTY5NTg3MTQ5Nn0.fdmIB_cv_Y3SmxsxtZEqPceTKI40I2rC5eiRnaHt4RI




#####
GET http://localhost:9000/api/seguimiento HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUxMGYzNDhhNjNjNzMzMzFkNmUxZTZlIiwidXNlcl9yb2xlIjoicmVndWxhciIsImlhdCI6MTY5NTg3MTQ5Nn0.fdmIB_cv_Y3SmxsxtZEqPceTKI40I2rC5eiRnaHt4RI









//POST REGISTER

#####
POST http://localhost:9000/api/register HTTP/1.1
Content-Type: application/json

{
    "nombreEmpresa": "empresa prueba 2",
    "nit": "1234",
    "numeroEmpleados": 14,
    "representanteLegal": "pepa",
    "actividadEconomica": "arte",
    "email": "prueba2@gmail.com",
    "password": "prueba2"
}




//POST LOGIN

#####
POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json


{
    "email": "prueba2@gmail.com",
    "password": "prueba2"
}